version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: db

    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: db-desafio
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"

    networks:
      - app-network
      
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    
    container_name: app

    ports:
      - "8082:8080"
    depends_on:
      - db

    # volumes:
    #   - ./:/

    networks:
      - app-network

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db-desafio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootPassword

networks:
  app-network:
    driver: bridge